### ISSUE TITLE
'receptor_CAs' is not defined in Notebook when using a structure other than the predefined one 

### ISSUE THREAD

**Issue by drchristhorpe** [patrickbryant1/EvoBind#1]
**Problem**

When I use a structure other than the predefined one, I get this error

NameError                                 Traceback (most recent call last)
[<ipython-input-14-7eb4089d2c46>](https://localhost:8080/#) in <module>()
     61 #Check if CALCULATE_BINDER_COM
     62 if CALCULATE_BINDER_COM==True:
---> 63   TARGET_CAs = receptor_CAs[np.array(TARGET_RESIDUES)-1]
     64   BINDER_COM = np.sum(TARGET_CAs,axis=0)/(TARGET_CAs.shape[0])
     65   RECEPTOR_CAs = prepare_input(OUTDIR+PDBID+".pdb", RECEPTOR_CHAIN, TARGET_RESIDUES, BINDER_COM, OUTDIR)

NameError: name 'receptor_CAs' is not defined

PDBID = "1q94" #@param {type:"string"}
RECEPTOR_CHAIN = "A" #@param {type:"string"}
RECEPTOR_SEQUENCE = "GSHSMRYFYTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDQETRNVKAQSQTDRVDLGTLRGYYNQSEDGSHTIQIMYGCDVGPDGRFLRGYRQDAYDGKDYIALNEDLRSWTAADMAAQITKRKWEAAHAAEQQRAYLEGRCVEWLRRYLENGKETLQRTDPPKTHMTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWE" #@param {type:"string"}
TARGET_RESIDUES = "5,7,9,24,25,33,34,45,59,62,63,64,65,66,67,68,69,70,72,73,74,75,76,77,78,80,81,84,95,97,99,114,116,123,124,133,139,140,142,143,144,146,147,152,155,156,157,158,159,160,163,164,167,168,171" #@param {type:"string"}
TARGET_RESIDUES = [int(x) for x in TARGET_RESIDUES.split(',')]
CALCULATE_BINDER_COM = True #@param {type:"boolean"}
BINDER_LENGTH =  9#@param {type:"integer"}
NITER =  300#@param {type:"integer"}
BINDER_COM = "33.966637,23.854908,9.859454" #@param {type:"string"}
BINDER_COM = [float(x) for x in BINDER_COM.split(',')]
RECEPTOR_MSA = "1q94_receptor.a3m" #@param {type:"string"}

I used an a3m from a previous AlphaFold run
**How to fix**

Change the variable name from receptor_CAs to RECEPTOR_CAs

**Comment by patrickbryant1** [comment]
Thanks for reporting this issue with the variable name.
