### ISSUE TITLE
singularity causes a FATAL error

### ISSUE THREAD

**Issue by aravindprasad** [patrickbryant1/EvoBind#10]
In setup.sh the following command causes an error
`singularity pull AF_environment.sif docker://catgumag/alphafold:latest`

The error is
`FATAL:   While making image from oci registry: failed to get checksum for docker://catgumag/alphafold:latest: Error reading manifest latest in docker.io/catgumag/alphafold: manifest unknown: OCI index found, but accept header does not support OCI indexes`

the docker pull command works fine
```
docker pull catgumag/alphafold:latest
latest: Pulling from catgumag/alphafold
eaead16dc43b: Pull complete 
f66018fd6918: Pull complete 
121ce45b8595: Pull complete 
5a5bda8264e7: Pull complete 
b05cc2528b1a: Pull complete 
7a8fd3721580: Pull complete 
7cdd51c189d4: Pull complete 
f43eb09af0d1: Pull complete 
6e59b32a7f85: Pull complete 
0b7e2150641d: Pull complete 
e82ea881eb2f: Pull complete 
4f4fb700ef54: Pull complete 
9c5bc5c2c45c: Pull complete 
Digest: sha256:8e9aaf56e4bbd23cef7d607ec5fee4dfddfa94eab79ff12b43bb31b90eba397f
Status: Downloaded newer image for catgumag/alphafold:latest
docker.io/catgumag/alphafold:latest
```

EDIT:
this might be a docker hub problem. The following command works
`singularity pull AF_environment.sif docker://catgumag/alphafold:2.3.1`
but the following commands do not
`singularity pull AF_environment.sif docker://catgumag/alphafold:2.3.2` and
`singularity pull AF_environment.sif docker://catgumag/alphafold:latest`

**Comment by patrickbryant1** [comment]
Yes, this may be related to some update. Singularity is now called 'apptainer' as well. We will probably migrate to conda in the future. An alternative is to simply install the AlphaFold environment: https://github.com/deepmind/alphafold/tree/main

**Comment by patrickbryant1** [comment]
There is now a conda option if you prefer that.

**Comment by aravindprasad** [comment]
Thanks @patrickbryant1

**Comment by patrickbryant1** [comment]
Evobind. Check the installation script.
