### ISSUE TITLE
Issue Executing Colab Notebook

### ISSUE THREAD

**Issue by MatiasValdes14** [patrickbryant1/EvoBind#11]
Dear Patrick
I hope this message finds you well, recently I tried to use Colab Notebook of Evobind and I used the test case but when the Colab goes to "Run Prediction", it crashes throwing the following error: 
XlaRuntimeError: INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gemm_algorithm_picker.cc:309) stream->parent()->GetBlasGemmAlgorithms(stream, &algorithms)

I don't know if it's an execution problem on my part or if it's broken internally

Greetings

**Comment by patrickbryant1** [comment]
Hi Matias,

This is related to an update from Google to a new CUDA version. We will try to rewrite the code to be compatible in Colab in the coming weeks.

Best,

Patrick

**Comment by patrickbryant1** [comment]
Should be fixed now - lmk if you have any other issues.

Best,

Patrick

**Comment by MatiasValdes14** [comment]
Thank you very much, I greatly appreciate the arrangement and availability, so far I haven't had any problems

Greetings,
Matías
