### ISSUE TITLE
Run EvoBind doesn't work

### ISSUE THREAD

**Issue by Sebaaax97** [patrickbryant1/EvoBind#12]
Hi:

I'm trying to use EvoBind from Google Colab but I'm having a problem. When I run the code cell "Run EvoBind" it is supposed to take 7 hours maximum, but I have done 23 hour tests and it has not given me any results. So far the only thing I have obtained is that message from libraries in which you can see in the image which I have attached.

Finally, I tried the tutorial associated with this GitHub and I have the same problem

![image](https://github.com/patrickbryant1/EvoBind/assets/158418648/99f20290-4f65-4aa4-ad6f-18859ec4e82b)

**Comment by patrickbryant1** [comment]
Hi, have you pressed "play" everywhere and are you using gpu? I don't see any output here.

**Comment by Sebaaax97** [comment]
> Hi, have you pressed "play" everywhere and are you using gpu? I don't see any output here.

Hi, yes I've been using GPU and pressed play

**Comment by patrickbryant1** [comment]
There is no error message here. Maybe you can try again?

**Comment by Sebaaax97** [comment]
> Hi, have you pressed "play" everywhere and are you using gpu? I don't see any output here.

I tried again, but I don't know why the "Run EvoBind" section takes so long (I even lowered the iterations from 300 to 100). I'm using the premium GPU options provided by Colab

**Comment by patrickbryant1** [comment]
Hi, 
Is this resolved? It may take a while to run the Colab version, but you have not provided any output.
