### ISSUE TITLE
cyclic_offset evobind notebook

### ISSUE THREAD

**Issue by LukasMezaa** [patrickbryant1/EvoBind#13]
Dear Patrick I was recently using EvoBind and got the following problem, I think it's because of a new update they have implemented... I don't know if you could guide me on how to solve this error. Thanks a lot
![problema](https://github.com/patrickbryant1/EvoBind/assets/144151382/052ae415-7ff3-4d4a-90dd-074316a7126b)

**Comment by patrickbryant1** [comment]
Dear Lucas,

Please do a new pull. I think there may have been some issues with a previous commit, but this should be fixed now.

Best,

Patrick

**Comment by LukasMezaa** [comment]
Dear Patrick
Thanks for replying, I've been checking and made a new release but I'm getting the same problem... As I'm currently using colab it's
1. I run to install dependencies, once they are installed, I restart
2. I make the EvoBind github clone
3. I try the mock test
4. I do the EvoBind Run and that is where the previously mentioned problem falls
I don't know if I'm doing something wrong, or if the aforementioned problem still persists.
Thank you so much.

**Comment by LukasMezaa** [comment]
> Dear Lucas,
> 
> Please do a new pull. I think there may have been some issues with a previous commit, but this should be fixed now.
> 
> Best,
> 
> Patrick

**Comment by LukasMezaa** [comment]
Dear Patrick
Thanks for replying, I've been checking and made a new release but I'm getting the same problem... As I'm currently using colab it's

1. I run to install dependencies, once they are installed, I restart
2. I make the EvoBind github clone
3. I try the mock test
4. I do the EvoBind Run and that is where the previously mentioned problem falls
I don't know if I'm doing something wrong, or if the aforementioned problem still persists.
Thank you so much.

**Comment by LukasMezaa** [comment]
I have tried it and so far it has worked for me with the test, I will try with my objective... thank you so much
