### ISSUE TITLE
Defining CM

### ISSUE THREAD

**Issue by Cucco23** [patrickbryant1/EvoBind#14]
Hi Patrick,

I have a question more than an issue. I was wondering how do you define the center of mass of the peptide. 
In my mind it should be the expected position of the CA of the middle amino acid of the peptide. 
However this position is a bit unpredictable especially if you do not start with a know surface. 

I was wondering how you guess this parameter and if I an estimating this correctly. 

How much this position affects the prediction? In other words, does this change during the evolution?

Thank you for the answer!

Ema

**Comment by patrickbryant1** [comment]
Hi,

I agree. There will be a new version of EvoBind out soon where you don't need this anymore.

Best,

Patrick

**Comment by Cucco23** [comment]
Looking forward for the new version!

Thank you for the quick response!

E

**Comment by patrickbryant1** [comment]
I close this issue since the new code is now available.
