### ISSUE TITLE
How aa are mutated?

### ISSUE THREAD

**Issue by Cucco23** [patrickbryant1/EvoBind#16]
Hi Patrick,

I have a couple of additional questions. 
1. How is the change of amino acid at each loop is defined? My understanding is that it is completely random. However if this is the case the machine has no memory of previous changes. Therefore peptides might be computed twice.  
2. How is chosen the amino acid in the peptide sequence that should be modified? 

Do you think that a computation of the pIddt of each aa or a running average of it, might be useful to define which aminoacid modify first to improve the binding?

Thank you for the answers, I found the software very nice! It is fun to test it. 

Ema

**Comment by patrickbryant1** [comment]
Hi,

1. There is "memory", only new sequences are evaluated.
2. Randomly
3. Maybe - try it out?

Thanks!

Best,

Patrick
