### ISSUE TITLE
Multichain target

### ISSUE THREAD

**Issue by SkwisgaarSkwigelf** [patrickbryant1/EvoBind#17]
Can a multichain (i.e. homo or heterodimer) structure be used as a target receptor? If so, how can interface hotspot residues be specified across 2 different chains?

**Comment by patrickbryant1** [comment]
Not as it is currently, but you can email me your specific issue and we can see if we can help. We find it's better not to specify hotspots and select for this later on.

**Comment by SkwisgaarSkwigelf** [comment]
Ok if that's the case can I just covert my entire multichain pdb into a single chain and consecutively number? Or will this mess up the MSA creation and AF filtering?

**Comment by patrickbryant1** [comment]
Yes, msas have to be adjusted accordingly.
