### ISSUE TITLE
Known starting structure

### ISSUE THREAD

**Issue by domgurvic** [patrickbryant1/EvoBind#18]
Hi Patrick,

Thanks for creating and sharing EvoBind, I had it running on few different proteins and the results are pretty interesting.

I was wondering if there is a way to manually select the starting composition of designed peptide that I want to improve, rather than starting from a random sequence?

Thanks!

Dom.

**Comment by patrickbryant1** [comment]
Hi,

Great to hear you like it!

Yes, you can write a metrics file with the starting sequence (run predict only) and then start from that or simply enter it in colab.

Best,

Patrick

**Comment by domgurvic** [comment]
Thanks for getting back to me so quick!

I changed `--predict_only=True` and added `--peptide_sequence="ACSFPKCGCA"` for the test case of 1ssc that you provided. 

But I can't seem to bypass it making a prediction but plddt score being zero and resulting in this error:

`    loss = if_dist_peptide*1/plddt
           ~~~~~~~~~~~~~~~~~^~~~~~
ZeroDivisionError: division by zero
` 

Also since it made a prediction and saved a structure unrelaxed_1.pdb I can see that the starting structure is not the one I provided with a flag but a random one. 

Any advice?

Best,

Dom.

**Comment by patrickbryant1** [comment]
Hi,

There was a bug - this should be fixed now. Please do a pull and try again.

Best,

Patrick

**Comment by domgurvic** [comment]
Hi,

You're right, its fixed now and it works exactly as you suggested with the starting structure.

Thank you. 
 
I'm happy to close this down but i do have another question regarding starting structure and distance to the target residues, is it best to open another thread?

Dom.
