### ISSUE TITLE
some issue bout python3 and singularity image

### ISSUE THREAD

**Issue by 18217265596** [patrickbryant1/EvoBind#2]
FATAL:   could not open image /dssg/home/acct-clswg/clswg/evobind/EvoBind/python3: failed to retrieve path for /dssg/home/acct-clswg/clswg/evobind/EvoBind/python3: lstat /dssg/home/acct-clswg/clswg/evobind/EvoBind/python3: no such file or director

**Comment by patrickbryant1** [comment]
It appears that your path to python is wrong? I don't see how this relates to EvoBind? Please open a specific issue for your error with EvoBind and provide more information about your error.
