### ISSUE TITLE
Adversarial AF-Multimer check implementation

### ISSUE THREAD

**Issue by mrJeppard** [patrickbryant1/EvoBind#22]
Hi there.

Was curious if the the 2nd loss function from Figure 1. b) of the preprint is implemented?

I couldn't find it in the collab or repository code.

Best

**Comment by patrickbryant1** [comment]
Hi,

We will add this shortly.

Best,

Patrick

**Comment by patrickbryant1** [comment]
It is added now. Try it out.
Note that this is for more advanced users and is not as "out of the box" as EvoBind.

**Comment by mrJeppard** [comment]
Thank you I appreciate it. Will report back after usage.
