### ISSUE TITLE
Use `aria2` instead of `wget` for faster uniclust30 download

### ISSUE THREAD

**Issue by shivashankarv** [patrickbryant1/EvoBind#23]
**Problem**: the current `wget http://wwwuser.gwdg.de/~compbiol/uniclust/2018_08/uniclust30_2018_08_hhsuite.tar.gz --no-check-certificate` in `setup.sh` takes >3hrs to download in most compute machines.

Replacing that line with the following code will help speed this up:

```
pip install aria2
aria2c -c -x `nproc` -s `nproc` --check-certificate=false http://wwwuser.gwdg.de/~compbiol/uniclust/2018_08/uniclust30_2018_08_hhsuite.tar.gz
```

**Comment by patrickbryant1** [comment]
It takes a few minutes for us. This must be related to your internet connection.
