### ISSUE TITLE
AFM Eval Features not the correct dimension

### ISSUE THREAD

**Issue by jvansan** [patrickbryant1/EvoBind#25]
Following up from #22 and #24 - the current implementation does not appear to be working correctly. I followed all instructions to setup the environment, and used the test files to re-generate the AFM features.  The resulting output has an `aatype` which appears as a `(123, 21)` 2D array instead of the  `(112,)` in the pre-computed features.

**Comment by patrickbryant1** [comment]
Hi,

I don't think this is an implementation problem. Likely you are providing the information incorrectly as the same scripts run for us. Can you please provide some more information about what you are inputting and the error you are getting and we can try to help.

Best,

Patrick

**Comment by jvansan** [comment]
Alright - thank you for confirming. I realized that I had deviated from the setup instructions in one step by using the v3 AFM parameters assuming they were just an updated version of v2.
