### ISSUE TITLE
TensorFlow 2.16 fails to recognize GPUs

### ISSUE THREAD

**Issue by ballaneypranav** [patrickbryant1/EvoBind#28]
Congratulations on your work! The EvoBind publication was excellent and I'm looking forward to trying it out! 

During installation, I've been having issues with TensorFlow 2.16. According to [#63362](https://github.com/tensorflow/tensorflow/issues/63362), TF 2.16 and 2.17 are unable to recognize GPUs. 

The environment.yml file for EvoBind specifies TF 2.16.2. I was wondering if you faced these issues during development, do you have any suggestions for workarounds? Have you tested EvoBind with any older versions of TF? 

Thanks!

**Comment by patrickbryant1** [comment]
Hi,

This is just a warning and tf is not using the GPU anyway. The installation should be fine with any of the tf versions. If it doesn't run, open an issue again and we'll try to help.

Best,

Patrick
