### ISSUE TITLE
about controlling output structure numbers

### ISSUE THREAD

**Issue by 18217265596** [patrickbryant1/EvoBind#3]
hi i wonder where the parameter of output numbers lie
and i changed NITER to 50 to test and it resulted in 49 unrelaxed structures
is that expexted?

**Comment by patrickbryant1** [comment]
Hi, the number of designed structures will correspond to the number of iterations. I am not sure why you obtain one less structure than specified. Perhaps this has something to do with resetting the number of iterations and restarting the run? The structures will be zero indexed so design number 50 will have index 49. If you want more structures you can simply increase the number of iterations.
