### ISSUE TITLE
SINGIMG in design_local.sh

### ISSUE THREAD

**Issue by tonigi** [patrickbryant1/EvoBind#4]
https://github.com/patrickbryant1/EvoBind/blob/68b8056ee26fc6fe9202903f05f3ef0f0d115c79/design_local.sh#L44

Should $IMG be $SINGIMG instead?

Otherwise one gets this

    FATAL:   could not open image /dgx/home/userexternal/tgiorgin/EvoBind/python3: failed to retrieve path for /dgx/home/userexternal/tgiorgin/EvoBind/python3: lstat /dgx/home/userexternal/tgiorgin/EvoBind/python3: no such file or directory

because "python" is taken as the image name. (This may be the same issue as https://github.com/patrickbryant1/EvoBind/issues/2 )

**Comment by patrickbryant1** [comment]
Yes, this variable name is wrong. This has now been updated. Thanks for reporting!
