### ISSUE TITLE
Faulty target interface

### ISSUE THREAD

**Issue by asaltala** [patrickbryant1/EvoBind#7]
Hello, 
I am trying to use the local version of the software, and what I noticed is that, with both the test case and my interested protein, when I specify a receptor target residue, the peptide location starts on a totally different location (so far so good) but it doesn't chage too much through the iterations. 
So for example, on the test case 1ssc.pdb, I have selected the residue 28 as target interface, however at each iteration the peptide is close to residue 108, that is on the opposite side of the protein. 

I have also tried asking for a 3 aa peptide, and after 80 iterations the peptide, although having a mutated sequence , it's still there. It's seems to me that the distance between the peptide COM and the receptor target COM it's not taken into account too much. 

Any help?

**Comment by patrickbryant1** [comment]
Hi,
The design process is stochastic and therefore unpredictable. This means that you may have to initialise several runs. Specifying only one residue is probably too little for optimisation. It may also be the case that the binding area you are targeting is hard to bind and another area may be more suitable. Running EvoBind - or any design software - requires expert knowledge.

I think that running 80 iterations is likely not enough to get a good estimate of the success. Try with 800 iterations and then evaluate.
